### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type long int

### ISSUE THREAD

**Issue by bzha5848** [1579093407/Yolov5_Magic#3]
Hi there,

I meet the following problem when I try to run your code
![image](https://user-images.githubusercontent.com/49177682/185764455-906fa7b9-207b-475e-89d7-b76a89063168.png)
How to solve it?

Thanks so much!!

**Comment by WangQvQ** [comment]
Maybe you should try PyTorch==1.11
