### ISSUE TITLE
对space_to_depth模块的疑问

### ISSUE THREAD

**Issue by vaerdu** [1579093407/Yolov5_Magic#5]
按照论文里结构图来说cat之后不是要进行一步卷积操作吗？
class space_to_depth(nn.Module):
    # Changing the dimension of the Tensor
    def __init__(self, dimension=1):
        super().__init__()
        self.d = dimension

    def forward(self, x):
         return torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1)

**Comment by WangQvQ** [comment]
这个就是官方提供的代码，我没有改动直接移植过来了，和论文里确实有点差距

**Comment by WangQvQ** [comment]
> 按照论文里结构图来说cat之后不是要进行一步卷积操作吗？ class space_to_depth(nn.Module): # Changing the dimension of the Tensor def **init**(self, dimension=1): super().**init**() self.d = dimension
> 
> ```
> def forward(self, x):
>      return torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1)
> ```

这个就是官方提供的代码，我没有改动直接移植过来了，和论文里确实有点差距
