### ISSUE TITLE
how to access csdn  blog? 

### ISSUE THREAD

**Issue by akashAD98** [1579093407/Yolov5_Magic#6]
not able to access csdn content, it would be great if you make it public on medium blog, we are ready to pay you as per your charges, your content quality is good but we cant able to make you payment & access blog from csdn. Thanks

@WangQvQ help is really appreciated

**Comment by WangQvQ** [comment]
> Thanks for your advice, it is really an interesting idea, so I plan to use Medium Blog recently, I will inform you after I find out the various ways of using Medium Blog.

**Comment by akashAD98** [comment]
@WangQvQ never saw the content like you, it's excellent quality. also, I saw your contributor in the #yoloair repo, please make your practical content available worldwide,

<img width="512" alt="image" src="https://user-images.githubusercontent.com/62583018/210498915-d49a9bc8-36f2-4d77-a670-66bbb28eece9.png">

also if possible please cover yolov7,yolov5 both .Thanks

2) Is this book available in English? sorry I'm asking this Q bcz not getting anyone from opensource platform,tried LinkedIn also,
https://yolov5.blog.csdn.net/article/details/127281760?spm=1001.2014.3001.5502

3) or is there any way to access the content of csdn outside china? really appreciated 
if anybody can help me with this please contact me with aksdesai1998@gmail.com

**Comment by WangQvQ** [comment]
1.  I just tried to publish a blog post on Medium, I hope it can help you. I am not very familiar with Medium now, and I will post other blog posts in the future：[https://medium.com/@1579093407/yolov5-v7-adding-attention-mechanics-tutorial-792800e68144](https://medium.com/@1579093407/yolov5-v7-adding-attention-mechanics-tutorial-792800e68144)

![image](https://user-images.githubusercontent.com/58406737/210530557-0bb8b168-e106-4426-a0ef-bef42dc3ea19.png)

2. There is no English version of this book at present. I wrote it by myself and have no plan to publish it at present. This book can be read on CSDN

**Comment by akashAD98** [comment]
@WangQvQ thanks a lot, This is perfect .can you provide pdf of this book,I’ll translate it to English, please mail me at aksdesai1998@gmail.com otherwise publish into a packet or somewhere else, I'm really looking for this book . I'm a big fan of your yolo series content

**Comment by WangQvQ** [comment]
@akashAD98 ummmm, Thank you for your support. This book has only been read by a few hundred people so far. I don't know if you have read the catalog, and I'm not sure if this book is right for you. The Blue Book is not free, I'm sorry, although I would love to let more people see my book.

**Comment by akashAD98** [comment]
@WangQvQ will pay for the book,or your csdn content, please ping me on mail regarding payment

**Comment by akashAD98** [comment]
@WangQvQ hi can you please tell me how can i access your content, can you publish how to read & write ,do changes in .yaml file in a medium blog?
